Pmpsupdate
pcdshub/lcls-plc-tmo-motion pull request #76
Opened 2023-03-10 02:44 UTC by tongju12

## New PMPS system in TMO motion without SP1K4 PMPS

Adding new PMPS library and fill in all states of each motor that matches the name is PMPS database
## Motivation and Context
 It is for SC in TMO and will let scientists change the beam class from database

https://jira.slac.stanford.edu/browse/LCLSECSD-1964
## How Has This Been Tested?

Test each target from every motor and check PMPS GUI

## Where Has This Been Documented?

https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=373331167

## Screenshots (if appropriate):

## Pre-merge checklist
- [ x] Code works interactively
- [ ] Code contains descriptive comments
- [x ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

2023-03-13 20:07 UTC, ZLLentz requested changes
Hi Tong, I found one typo in IM3K4 and some oddity in TM2K4's loading as seen in the client GUI. The rest looked good. I had some additional notes and small questions.

2023-03-13 20:07 UTC, ZLLentz commented on plc-tmo-motion/tmo_motion/POUs/TM2K4/ENUM_TM2K4_States.TcDUT
> +	TARGET5 := 6
Small question: why are these called TARGET4 and TARGET5 on the ATMs in the enum here, but YAG and DIODE in the database states? You could always rename these here if you wanted.

2023-03-13 20:07 UTC, ZLLentz commented on plc-tmo-motion/tmo_motion/POUs/PRG_TM2K4.TcPOU
> +fbTM2K4.stTarget5.stPMPS.sPmpsState := 'TM2K4:ATM-DIODE';
Hi Tong, did target 5 here (diode) load and run correctly in the PLC? It doesn't show up in my diagnostic in the IOC, so either there was a load issue or something weird happened with the IOC build. Let me know if I should debug the diagnostic GUI.
![image](https://user-images.githubusercontent.com/10647860/224820007-5484a0ee-8ffc-4ae2-94e4-ae316aff0697.png)

2023-03-16 18:16 UTC, tongju12 commented on plc-tmo-motion/tmo_motion/POUs/PRG_1_PlcTask.TcPOU
> +//PRG_SP1K4();
Yes, TMO knew it and it is ok with us now.

2023-03-16 18:17 UTC, tongju12 commented on plc-tmo-motion/tmo_motion/POUs/PRG_IM3K4_PPM.TcPOU
> +fbIM3K4.stYag1.stPMPS.sPmpsState := 'IM3K4:PPM-YAG2';
It was a mistake. I fix it in the new commit. Thanks!

2023-03-16 18:18 UTC, tongju12 commented on plc-tmo-motion/tmo_motion/POUs/PRG_TM2K4.TcPOU
> +fbTM2K4.stTarget5.stPMPS.sPmpsState := 'TM2K4:ATM-DIODE';
Yes, TM2K4 targt 5 is working well in PLC and PMPS main screen can watch it while it is moving but somehow this client GUI does not show target 5 though.

2023-03-17 16:57 UTC, ZLLentz commented on plc-tmo-motion/tmo_motion/POUs/PRG_TM2K4.TcPOU
> +fbTM2K4.stTarget5.stPMPS.sPmpsState := 'TM2K4:ATM-DIODE';
I'm creating an issue in my repo to investigate this later: https://github.com/pcdshub/pmpsdb_client/issues/20

2023-03-17 16:58 UTC, ZLLentz approved these changes
Updated from suggestions and the important CI jobs pass :+1:

2023-03-17 18:12 UTC, merged